# Generated by Django 2.2 on 2022-04-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='covid_news',
        ),
    ]
