# Generated by Django 2.2 on 2022-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_covid_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('content', models.CharField(max_length=10000)),
                ('keywords', models.CharField(max_length=10000)),
                ('url', models.CharField(max_length=10000)),
                ('img', models.CharField(max_length=10000)),
                ('public_date', models.CharField(max_length=10000)),
            ],
        ),
    ]
