# Generated by Django 2.2 on 2022-04-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20220427_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='covid_news',
        ),
    ]
