# Generated by Django 2.2 on 2022-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_covid_news_tag_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_links_news',
            name='tag_news',
            field=models.CharField(default='dantri.com.vn', max_length=100),
        ),
    ]
